### ISSUE TITLE
[BUG] Camera is mirrored

### ISSUE THREAD

**Issue by aceschen** [calblueprint/meepanyar#110]
**Describe the bug**
The camera on the purchase request feature shows a mirror image. Image uploads mirrored as well.

**To Reproduce**
1. Select an inventory item
2. Click purchase to make a request
3. Click add photo

**Expected behavior**
Camera should not be mirrored, since it makes text unreadable.

**Screenshots**
Uploaded a picture of text under a purchase request for Bread!

**Device (please complete the following information):**
 - Device Model: Pixel 2
 - OS: Android 11

**Environment:**
Which environment(s) is this bug located in?
- i dont know im sorry 
- Using the Netlify app

CC: @julianrkung

**Comment by kwfk** [comment]
![image](https://user-images.githubusercontent.com/9738398/115131002-445a7380-9fa9-11eb-826e-bf9d5ab27b65.png)

**Comment by julianrkung** [comment]
Looks like easy fix by passing `isImageMirror` property

https://www.npmjs.com/package/react-html5-camera-photo
