### ISSUE TITLE
[BUG] Starting meter shouldn't be larger than ending meter

### ISSUE THREAD

**Issue by kwfk** [calblueprint/meepanyar#113]
**Describe the bug**
There is no input validation for when setting the starting meter number going above the ending meter number. Also, vice versa when setting the ending meter to below the starting meter This can result in a negative period usage which doesn't make sense.

**To Reproduce**
1. Create a new customer with a fixed tariff, **0 unit tariff**, and **0 free units**
2. Set a Last Recorded Reading
3. Change the starting meter to a number above the ending meter
4. The Period Usage becomes a negative number
5. You can also change the Ending Meter to something that is below the Starting Meter

**Expected behavior**
There should be a check so that the Starting Meter can't be above the Ending Meter and the Ending Meter can't be below the Starting Meter.

**Screenshots**
![image](https://user-images.githubusercontent.com/9738398/115131008-54725300-9fa9-11eb-92df-538a024224fe.png)

**Device (please complete the following information):**
 - Device Model: Samsung S9
 - OS: Android 10

**Environment:**
Which environment(s) is this bug located in?
local/development
✅ production

CC: @julianrkung

**Comment by julianrkung** [comment]
Thanks for submitting the issue. Will be fixed in: https://github.com/calblueprint/meepanyar/pull/123
