### ISSUE TITLE
[BUG] Customer Search breaks during backspace

### ISSUE THREAD

**Issue by julianrkung** [calblueprint/meepanyar#128]
**Describe the bug**

**To Reproduce**
1. I created a customer called "Offline Customer"
2. On the customer search, I searched "Oi" and no customers should show up because none start with "Oi"
3. Press backspace so the customer search is now only "O" and offline customer SHOULD show up but doesn't
4. You can also type in "Of" from this point and notice that offline customer still doesn't show up, you must completely clear the search "" and begin typing again for search to work.

**Expected behavior**
Search should be responsive and correct at all times. At step 3, the customer "Offline Customer" should show up

**Screenshots**
Video: https://www.loom.com/share/5dfed9234d2b485dbccc2da77937d69f

**Device (please complete the following information):**
 - Device Model: [e.g. iPhone6]

**Environment:**
Which environment(s) is this bug located in?
- local or development
- production

If the bug is located in production, find the version number under Menu > Settings 
- Version [e.g. 1.1.0]

**Additional context**

CC: @julianrkung

**Comment by julianrkung** [comment]
Looks like this same problem doesn't happen in Inventory's search, so should be a quick fix if you can see what's the difference between the 2!

**Comment by cnnmon** [comment]
I don't get this bug
When backspacing:
![image](https://user-images.githubusercontent.com/20329981/115969058-e6211980-a4ef-11eb-84cb-de1a2e30303e.png)
