### ISSUE TITLE
Empty customer names break sorting

### ISSUE THREAD

**Issue by wangannie** [calblueprint/meepanyar#95]
Empty customer names in Airtable break the app:
![image](https://user-images.githubusercontent.com/21160510/114812638-3d432380-9d65-11eb-8451-53d2abbcac48.png)

![image](https://user-images.githubusercontent.com/21160510/114812584-23094580-9d65-11eb-8529-60ce2f7a05ee.png)

This is probably happening in `return customerA.name.localeCompare(customerB.name)` on [Line 123 of CustomerMain](https://github.com/calblueprint/meepanyar/blob/main/src/screens/Customers/CustomerMain.tsx#L123).

**Comment by julianrkung** [comment]
Fixed in https://github.com/calblueprint/meepanyar/pull/85
